### ISSUE TITLE
Clean up repository

### ISSUE THREAD

**Issue by t0pg3ar** [t0pg3ar/dual-lingo-user-models-2020#22]
Clean up repository, remove all files that are left from the original fork like the iPython Notebook.

**Comment by IDMAkrum** [comment]
Data example file doesn't match what our data should look like. Do we change the example or delete file?

**Comment by t0pg3ar** [comment]
We should delete it imho, it's a remnant of the old code

**Comment by Fuithof** [comment]
Repository seems to be cleaned
