### ISSUE TITLE
Check edited instructions in repository

### ISSUE THREAD

**Issue by t0pg3ar** [t0pg3ar/dual-lingo-user-models-2020#23]
Add a readme for handing in the results of the experiment (age, preferred gender, nativeness etc)

**Comment by IDMAkrum** [comment]
Hand-in instructions added, do we want any other info besides agef, gender, and nativeness?

**Comment by t0pg3ar** [comment]
I wouldn't say so. @Fuithof?

**Comment by Fuithof** [comment]
'how to hand in' is moved to right under the disclaimer, 'run the experiment' has been edited.

**Comment by t0pg3ar** [comment]
Seems to be alright indeed. I'll close the issue.
